### ISSUE TITLE
Tabs has a warning about not recognizing `menuIndex`.

### ISSUE THREAD

**Issue by danneSvall** [Sundsvallskommun/web-shared-components#259]
Warning: React does not recognize the `menuIndex` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `menuindex` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by jerkerosatiesk** [comment]
Kan ej återskapa problem.
